# Generated by Django 5.0.6 on 2024-07-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('eventDate', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('agenda', models.TextField()),
                ('speakers', models.TextField()),
                ('total_num_of_seats', models.IntegerField()),
                ('registered_seats', models.IntegerField(default=0)),
                ('remaining_seats', models.IntegerField(editable=False)),
            ],
        ),
    ]
