# Generated by Django 5.0.6 on 2024-07-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='remaining_seats',
            field=models.IntegerField(),
        ),
    ]
