# Generated by Django 5.0.7 on 2024-07-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_profile_is_logged_out_profile_logout_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user_attended',
            field=models.BooleanField(default=False),
        ),
    ]
