# Generated by Django 5.0.7 on 2024-07-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_registration_user_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
