# Generated by Django 5.0.7 on 2024-07-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_registration_user_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile_no',
            new_name='phone_number',
        ),
    ]
