# Generated by Django 5.0.7 on 2024-07-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_registration_user_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='mobile_no',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
